#### virtual hosts configuration ####
virtual_hosts:
  - listen: 80
    server_name: example.com
    index: index.html
    index_template_path: index.html.j2
    location: 
      - name: '\'
        content: "try_files $uri $uri/ =404;"
sites_root: /var/www
#### ssl ####
private_key_dir: /etc/ssl/private/
cert_dir: /etc/nginx/ssl/
csr_dir: /etc/ssl/csr/
local_secrets_dir: ./secrets/
challenges_dir: /var/www/challenges/
ssl_pass_dir: /etc/nginx/ssl_pass/
ssl_redirect: true
#### ssl renew ####
ssl_renew: true
renew_minute: "0"
renew_hour: "1"
renew_day: "1"
renew_weekday: "*"
renew_month: "*"