---
- name: Install Nginx
  ansible.builtin.apt:
    name: "{{ package_name }}"
    update_cache: true
    state: present

- name: Start and enable Nginx
  ansible.builtin.systemd:
    name: nginx
    enabled: true
    state: started
  
- name: Add Nginx configuration file
  ansible.builtin.template:
    src: "nginx.conf.j2"
    dest: "/etc/nginx/nginx.conf"
    owner: root
    group: root
    mode: '0700'
  notify: Nginx reload

- name: Create root sites directories
  ansible.builtin.file:
    path: "{{ sites_root }}/{{ item.server_name}}"
    state: directory
    owner: www-data
    group: www-data
    mode: 0700
  loop: "{{ virtual_hosts }}"

- name: Add example index pages to site root
  ansible.builtin.template:
    src: "{{ item.index_template_path | default('index.html.j2') }}"
    dest: "{{ sites_root }}/{{ item.server_name}}/{{ item.index}}"
    owner: www-data
    group: www-data
    mode: 0600
  loop: "{{ virtual_hosts }}"
  notify: Nginx reload
  when: 
    - item.index is defined

- name: Add VirtualHosts configuration
  ansible.builtin.template:
    src: site.conf.j2
    dest: /etc/nginx/sites-available/{{ item.server_name }}.conf
    owner: root
    group: root
    mode: 0640
  loop: "{{ virtual_hosts }}"
  notify: Nginx reload

- name: Enable VirtualHost configuration
  ansible.builtin.file:
    src: /etc/nginx/sites-available/{{ item.server_name }}.conf
    dest: /etc/nginx/sites-enabled/{{ item.server_name }}
    state: link
  loop: "{{ virtual_hosts }}"
  notify: Nginx reload